### PR TITLE
Allows support to Laravel 5.1

### PR DESCRIPTION
**Pull request by lucasmichot**
Provides support Laravel 5.1

### CODE REVIEW

**Comment by lucasmichot** [comment]
:+1: looking forward to get this package in stable version

**Comment by andersao** [comment]
Soon, I'll just do some testing ;)

**Comment by andersao** [comment]
@lucasmichot  version 2.0.13 released

**Comment by lucasmichot** [comment]
Thanks @andersao !

**Comment by jartaud** [comment]
Thanks!

**Pull request merged**
